# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Rui Wang
title: Ph.D. Candidate in Civil and Environmental Engineering, Princeton University
email: ruiw@princeton.edu
phone: +1 (609) 955-8833
website: https://sites.google.com/view/rui-wang/

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: rui-wang-7233631a9
orcid_username: 0000-0003-0588-1524

# Additional icon links
additional_links:
 - title: ResearchGate
   icon: /images/research_gate.png
   url: https://www.researchgate.net/profile/Rui_Wang349

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: <strong>About Me</strong>
about_profile_image: /images/Rui Wang.jpg
about_content: | # this will include new lines to allow paragraphs
  I am currently a Ph.D. Candidate in CEE department at Princeton University, working with <a href="https://www.google.com/url?q=http%3A%2F%2Fzondlo.princeton.edu%2Findex.html&sa=D">Prof. Mark Zondlo</a>. I am interested in utilizing multiple atmospheric ammonia (NH<sub>3</sub>) datasets, including satellite observations, ground monitoring network, and in-situ measurements, to understand ammonia's impact on air pollution.

# Projects Section
projects_title: <strong>Publications</strong> #(Use this to override about projects section title)

# Experience Section
experience_title: <strong>Research Experience</strong> #(Use this to override about experience section title)

# Education Section
education_title: <strong>Education</strong> #(Use this to override about education section title)

# More Section
more_title: <strong>Significant Presentations</strong> #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
