# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Rui Wang
title: Ph.D. Candidate in Civil and Environmental Engineering, Princeton University
email: ruiw@princeton.edu
phone: +(01) 609-955-8833
website: https://sites.google.com/view/rui-wang/

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: rui-wang-7233631a9
orcid_username: 0000-0003-0588-1524

# Additional icon links
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: <strong>About Me</strong>
about_profile_image: /images/Rui Wang.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a Ph.D. Candidate in the CEE department in Princeton University, working with <a href="http://zondlo.princeton.edu/index.html">Prof. Mark Zondlo</a>.

# Projects Section
projects_title: <strong>Publications</strong> #(Use this to override about projects section title)

# Experience Section
experience_title: <strong>Research Experience</strong> #(Use this to override about experience section title)

# Education Section
education_title: <strong>Education</strong> #(Use this to override about education section title)

# More Section
more_title: <strong>Significant Presentations</strong> #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
